"""create image table, add url column

Revision ID: 31a58db31ce5
Revises: 7e6898f4fbbb
Create Date: 2026-03-30 15:42:10.926090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a58db31ce5'
down_revision: Union[str, Sequence[str], None] = '7e6898f4fbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'url')
    # ### end Alembic commands ###
