"""add additional column for techs and images table

Revision ID: bba8e6c0b11c
Revises: 31a58db31ce5
Create Date: 2026-03-31 11:01:03.845068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba8e6c0b11c'
down_revision: Union[str, Sequence[str], None] = '31a58db31ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('alt_text', sa.String(), nullable=False))
    op.add_column('techs', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'techs', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'techs', type_='unique')
    op.drop_column('techs', 'slug')
    op.drop_column('images', 'alt_text')
    # ### end Alembic commands ###
